# Generated by Django 2.1.4 on 2018-12-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_author_publishe_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='index.Author'),
        ),
    ]
